### ISSUE TITLE
prismic-configuration.js

### ISSUE THREAD

**Issue by w-stegmann** [lhbzr/bruno-arizio#1]
Maybe you should add prismic-configuration.js to .gitignore?

**Comment by lhbzr** [comment]
Damn, thanks for the tip, I really forgot to remove it from the project. 😂

**Comment by lhbzr** [comment]
Just removed the file @w-stegmann, thanks a lot for spotting it and creating the first issue on the project! Did the code here helped you in any way so far? 😄

**Comment by w-stegmann** [comment]
@lhbzr, thanks for sharing the project. I wasn't able to get the Prismic part right, so I used the credentials of Bruno for a test build. 🙈 Some further explanation would be helpful if you have the time and motivation for it.

**Comment by lhbzr** [comment]
@w-stegmann HAHA, I'm glad you made it work on your machine! 😂 That would be very good indeed, I'll prepare some better documentation to run it when I have some time, right now I'm too busy with too many projects, but thanks again for opening this issue!
